"""
Early-season fallback predictions.

`generate_predictions()` builds player averages out of this season's 60+ minute
appearances, so it produces nothing until a few gameweeks have been played. This
module supplies a stand-in for that window: a pre-computed CSV of proxy
predictions (price-based baseline x fixture-difficulty multiplier), generated by
the fpl-lad `proxy-points-predictions` skill and committed to `data/`.

Two pieces are needed, because the rest of the pipeline leans on `gw_data` for
more than just predictions:

  load_proxy_predictions()  reshapes the CSV into the frame the solver and
                            watchlist expect
  synthesize_gw_data()      builds a gw_data-shaped frame from bootstrap-static,
                            since create_watchlist() reads player costs from it
                            and solver.load_player_data() reads name/position/value

See `data/proxy_predictions.csv` and the skill's SKILL.md for how the numbers are
derived and what they do and don't account for.
"""

import logging
from pathlib import Path
from typing import Iterable, List, Optional, Tuple

import pandas as pd

logger = logging.getLogger(__name__)

PROXY_PREDICTIONS_FILE = "proxy_predictions.csv"

# Mirrors fpl/predict.py's PREDICTION_COMPONENTS shape closely enough for the
# solver, which only ever groups by (element, event) and sums predicted_points.
_PROXY_COMPONENT = "proxy_total"


def proxy_predictions_available(data_dir: Path) -> bool:
    return (Path(data_dir) / PROXY_PREDICTIONS_FILE).exists()


def deadline_passed_for_gw(bootstrap: dict, gw: int) -> Optional[bool]:
    """
    Has GW `gw`'s deadline passed?

    Returns None when the gameweek isn't in bootstrap at all (so callers can
    distinguish "unknown" from "no"), otherwise a bool taken from the FPL API's
    own per-event flags rather than comparing clocks locally.
    """
    for event in bootstrap.get("events", []):
        if event.get("id") == gw:
            # `finished`/`is_current` imply the deadline is behind us; for a
            # future event FPL still exposes deadline_time, so fall back to that.
            if event.get("finished") or event.get("is_current"):
                return True
            deadline = event.get("deadline_time")
            if deadline:
                return pd.Timestamp.utcnow() >= pd.Timestamp(deadline)
            return False
    return None


def should_use_proxy(bootstrap: dict, threshold_gw: Optional[int], data_dir: Path) -> bool:
    """
    True when predictions should come from the proxy CSV rather than from
    this season's history.

    The rule: while GW `threshold_gw`'s deadline has NOT passed, use the proxy.
    Once it has, the season has enough played fixtures for the real pipeline.
    """
    if not threshold_gw:
        return False

    if not proxy_predictions_available(data_dir):
        logger.warning(
            "points_pred_gw_threshold=%s is set but %s is missing from %s — "
            "falling back to the normal prediction pipeline",
            threshold_gw, PROXY_PREDICTIONS_FILE, data_dir,
        )
        return False

    passed = deadline_passed_for_gw(bootstrap, threshold_gw)
    if passed is None:
        logger.warning("GW %s not found in bootstrap events — not using proxy predictions",
                       threshold_gw)
        return False

    if passed:
        logger.info("GW %s deadline has passed — using normal predictions", threshold_gw)
        return False

    logger.info("GW %s deadline has not passed — using proxy predictions from %s",
                threshold_gw, PROXY_PREDICTIONS_FILE)
    return True


def load_proxy_predictions(data_dir: Path, fixtures: Optional[pd.DataFrame] = None) -> pd.DataFrame:
    """
    Load proxy predictions and shape them like generate_predictions() output.

    The CSV is one row per player-fixture. The solver groups by (element, event)
    and sums, so double gameweeks are handled by simply keeping both rows.
    """
    path = Path(data_dir) / PROXY_PREDICTIONS_FILE
    df = pd.read_csv(path)

    if "player_team_id" not in df.columns:
        raise ValueError(
            f"{path} is missing 'player_team_id'. solver.load_player_data() joins on it. "
            "Regenerate the CSV with the proxy-points-predictions skill."
        )

    out = pd.DataFrame({
        "element": df["player_id"].astype(int),
        "name": df["name"],
        "position": df["position"],
        "event": df["event"].astype(int),
        # solver.load_player_data() takes this frame as `normalized_data` and
        # reads player_team_id off it.
        "player_team_id": df["player_team_id"].astype(int),
        "predicted_points": df["predicted_points"].astype(float),
        "component_type": _PROXY_COMPONENT,
        # No appearance history exists yet — see synthesize_gw_data().
        "hist_games": 0,
    })

    for col in ("team", "opponent", "opponent_team_id", "is_home", "price"):
        if col in df.columns:
            out[col] = df[col]

    logger.info("Loaded %d proxy predictions (%d players, GW %d-%d) from %s",
                len(out), out["element"].nunique(), out["event"].min(),
                out["event"].max(), path)
    return out


def synthesize_gw_data(bootstrap: dict, as_of_gw: int = 1) -> pd.DataFrame:
    """
    Build a minimal gw_data-shaped frame from bootstrap-static.

    Pre-season the real gw_data is empty, but create_watchlist() needs player
    costs and solver.load_player_data() needs name/position/value keyed by
    element. This supplies exactly those, marked as a single synthetic
    gameweek.

    `minutes` is set to 90 so nothing is filtered out by minutes-based checks:
    with no appearances on record there is no basis to rank availability, and
    the proxy model already assumes every player features. Callers should pair
    this with min_hist_pct=0.0 — see run.py.
    """
    rows = [
        row for row in (
            _bootstrap_gw_row(e, as_of_gw, minutes=90)
            for e in bootstrap.get("elements", [])
        )
        if row is not None
    ]

    df = pd.DataFrame(rows)
    logger.info("Synthesized gw_data for %d players from bootstrap (no real history yet)", len(df))
    return df


POSITION_BY_ELEMENT_TYPE = {1: "GK", 2: "DEF", 3: "MID", 4: "FWD"}


def _bootstrap_gw_row(element: dict, as_of_gw: int, minutes: int) -> Optional[dict]:
    """One gw_data-shaped row for a bootstrap element, or None if it has no position."""
    position = POSITION_BY_ELEMENT_TYPE.get(element.get("element_type"))
    if position is None:
        return None
    return {
        "element": element["id"],
        "name": f"{element.get('first_name', '')} {element.get('second_name', '')}".strip(),
        "position": position,
        "team": element.get("team"),
        "value": element.get("now_cost"),
        "GW": as_of_gw,
        "round": as_of_gw,
        "minutes": minutes,
    }


def ensure_players_present(
    gw_data: pd.DataFrame,
    required_ids: Iterable[int],
    bootstrap: dict,
    as_of_gw: int = 1,
) -> Tuple[pd.DataFrame, List[int]]:
    """
    Guarantee gw_data holds at least one row for every id in `required_ids`.

    The current squad has to be in the solver's player pool, or the model is not
    merely suboptimal — it is INFEASIBLE. load_player_data() builds the pool from
    gw_data; Squad_Size pins ownership at exactly 15 in every gameweek; and the
    transfer-count constraints force transfers-in to equal transfers-out. So 14
    owned players can never become 15: every scenario returns INFEASIBLE and the
    whole run dies with "No feasible solution found", which tells the user nothing
    about what happened or which player caused it.

    A squad member with no history is an ordinary thing, not a corrupt state: a
    mid-season signing bought the day FPL registers him has no per-fixture rows
    until his club next plays, and any sync gap does the same for anyone.
    create_watchlist() already resurrects must-include players missing from
    PREDICTIONS, but it reads their price out of gw_data — so it cannot help
    someone missing from gw_data too, and silently skips them while logging that it
    added them.

    Call this AFTER generate_predictions(), never before: these rows carry no real
    appearance and would otherwise be folded into the per-player averages that
    predictions are built from.

    `minutes=0` marks them as what they are, so nothing mistakes one for an
    appearance. The player is added to be ownable and sellable, not to be
    recommended — he arrives with no predicted points and the solver is free to
    transfer him out.

    Returns:
        (gw_data, still_missing) — still_missing lists ids bootstrap does not know
        either, which cannot be synthesized and will still break the solve.
    """
    required = list(dict.fromkeys(required_ids))
    if not required:
        return gw_data, []

    present = set(gw_data["element"].tolist()) if len(gw_data) else set()
    missing = [pid for pid in required if pid not in present]
    if not missing:
        return gw_data, []

    by_id = {int(e["id"]): e for e in bootstrap.get("elements", []) if "id" in e}
    rows = []
    still_missing = []
    for pid in missing:
        element = by_id.get(int(pid))
        row = _bootstrap_gw_row(element, as_of_gw, minutes=0) if element else None
        if row is None:
            still_missing.append(pid)
        else:
            rows.append(row)

    if rows:
        gw_data = pd.concat([gw_data, pd.DataFrame(rows)], ignore_index=True)
        logger.warning(
            "Synthesized gw_data rows for %d squad player(s) with no history: %s. "
            "They are ownable with no predicted points; without this the solve is infeasible.",
            len(rows), [r["element"] for r in rows],
        )
    if still_missing:
        logger.error("bootstrap has no entry for squad player(s) %s", still_missing)

    return gw_data, still_missing
